---
output:
  pdf_document:
    latex_engine: xelatex
    number_sections: false
    toc: false
    includes:
      in_header: shared.tex
fontsize: 11pt
geometry: margin=2.15cm
header-includes:
  - \pagenumbering{gobble}
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)
```

\nameheader{Publication list}

\contactline{%
Daniel Goller, Ph.D. \enspace \enspace $\cdot$ \enspace \enspace
\iconhref{\faGlobe}{https://dangoll.github.io/index.html}{Personal Webpage}
\enspace \enspace $\cdot$ \enspace \enspace
\iconhref{\faLinkedin}{https://www.linkedin.com/in/daniel-goller-a50b76197}{LinkedIn}
\enspace \enspace $\cdot$ \enspace \enspace
\iconhref{\faGlobe}{https://scholar.google.com/citations?user=5U7ldvQAAAAJ&hl=de}{Google Scholar}%
}

# Current Work and Working Papers

## Current Work (unpublished)

\begin{itemize}
\item ``Gender differences in beliefs about productivity-relevant skills'', with E.\ Brox and S.C.\ Wolter
\item ``Which Skills Matter Most for Early Labor Market Success?'', with R.\ Sartore
\item ``Skills Mismatch: Measurement and Consequences''
\end{itemize}

## Working Papers

\begin{itemize}
\item Goller, Daniel, Enzo Brox, and Stefan C.\ Wolter (2026) ``Imperfect Self-knowledge about Skills and Skill Mismatch.'' \textit{Swiss Leading House Working Paper}, No.\ 253. 
\item Späth, Maximilian, and Daniel Goller (2023). ``Gender differences in investment reactions to irrelevant information.'' \textit{CEPA Discussion Papers}, No.\ 67. DOI: \href{https://doi.org/10.25932/publishup-60635}{10.25932/publishup-60635}.
\end{itemize}

# Published Work

## 2026

\begin{itemize}
\item Brox, Enzo, and Daniel Goller (2026). ``Tournaments, Contestant Heterogeneity and Performance.'' \textit{Journal of Political Economy: Microeconomics}, 4 (2), 583--619. DOI: \href{https://doi.org/10.1086/735786}{10.1086/735786}.
\item Goller, Daniel (2026). ``Reaching for the stars from the top of the ladder? Rank, gender, and future aspirations'' \textit{Economics Letters}, 265, 113015. DOI: \href{https://doi.org/10.1016/j.econlet.2026.113015}{10.1016/j.econlet.2026.113015}.
\end{itemize}

## 2025

\begin{itemize}
\item Goller, Daniel, and Stefan C.\ Wolter (2025). ``Reaching for gold! The impact of a positive reputation shock on career choice.'' \textit{European Economic Review}, 175, 105017. DOI: \href{https://doi.org/10.1016/j.euroecorev.2025.105017}{10.1016/j.euroecorev.2025.105017}.
\item Goller, Daniel, Chiara Graf, and Stefan C.\ Wolter (2025). ``Virtual vs.\ in-person career fairs: the impact on search activity and diversity.'' \textit{Applied Economics Letters}, 1--4. DOI: \href{https://doi.org/10.1080/13504851.2025.2462708}{10.1080/13504851.2025.2462708}.
\item Goller, Daniel, Christian Gschwendt, and Stefan C.\ Wolter (2025). ``This time it’s different -- Generative artificial intelligence and occupational choice.'' \textit{Labour Economics}, 95, 102746. DOI: \href{https://doi.org/10.1016/j.labeco.2025.102746}{10.1016/j.labeco.2025.102746}.
\item Goller, Daniel, Michael Lechner, Tamara Pongratz, and Joachim Wolff (2025). ``Active labor market policies for the long-term unemployed: New evidence from causal machine learning.'' \textit{Labour Economics}, 94, 102729. DOI: \href{https://doi.org/10.1016/j.labeco.2025.102729}{10.1016/j.labeco.2025.102729}.
\end{itemize}

## 2024

\begin{itemize}
\item Goller, Daniel, and Maximilian Späth (2024). ``Good job! The impact of positive and negative feedback on performance.'' \textit{Sports Economics Review}, 8, 100045. DOI: \href{https://doi.org/10.1016/j.serev.2024.100045}{10.1016/j.serev.2024.100045}.
\item Goller, Daniel, and Sandro Heiniger (2024). ``A general framework to quantify the event importance in multi-event contests.'' \textit{Annals of Operations Research}, 341(1), 71--93. DOI: \href{https://doi.org/10.1007/s10479-023-05540-x}{10.1007/s10479-023-05540-x}.
\end{itemize}

## 2023

\begin{itemize}
\item Goller, Daniel, Andrea Diem, and Stefan C.\ Wolter (2023). ``Sitting next to a dropout: Academic success of students with more educated peers.'' \textit{Economics of Education Review}, 93, 102372. DOI: \href{https://doi.org/10.1016/j.econedurev.2023.102372}{10.1016/j.econedurev.2023.102372}.
\item Goller, Daniel (2023). ``Analysing a built-in advantage in asymmetric darts contests using causal machine learning.'' \textit{Annals of Operations Research}, 325(1), 649--679. DOI: \href{https://doi.org/10.1007/s10479-022-04563-0}{10.1007/s10479-022-04563-0}.
\end{itemize}

## 2021

\begin{itemize}
\item Goller, Daniel, and Stefan C.\ Wolter (2021). ``Too shocked to search: The COVID-19 shutdowns’ impact on the search for apprenticeships.'' \textit{Swiss Journal of Economics and Statistics}, 157, Article 6. DOI: \href{https://doi.org/10.1186/s41937-021-00075-z}{10.1186/s41937-021-00075-z}.
\item Goller, Daniel, Michael C.\ Knaus, Michael Lechner, and Gabriel Okasa (2021). ``Predicting match outcomes in football by an Ordered Forest estimator.'' In Ruud H.\ Koning and Stefan Kesenne (eds.), \textit{A Modern Guide to Sports Economics}, Chapter 22, pp.\ 335--355. Edward Elgar Publishing. DOI: \href{https://doi.org/10.4337/9781789906530.00026}{10.4337/9781789906530.00026}.
\end{itemize}

## 2020

\begin{itemize}
\item Goller, Daniel, and Alex Krumer (2020). ``Let’s meet as usual: Do games played on non-frequent days differ? Evidence from top European soccer leagues.'' \textit{European Journal of Operational Research}, 286(2), 740--754. DOI: \href{https://doi.org/10.1016/j.ejor.2020.03.062}{10.1016/j.ejor.2020.03.062}.
\item Goller, Daniel, Michael Lechner, Andreas Moczall, and Joachim Wolff (2020). ``Does the estimation of the propensity score by machine learning improve matching estimation? The case of Germany's programmes for long term unemployed.'' \textit{Labour Economics}, 65, 101855. DOI: \href{https://doi.org/10.1016/j.labeco.2020.101855}{10.1016/j.labeco.2020.101855}.
\end{itemize}
